version: '3.5'
services:
  imbabetfe:
    image: 1337festor/imbabetweb:latest
    container_name: imbabet
    restart: unless-stopped
    ports:
      - 8111:8080
      - 8112:8081
    environment:
      - ConnectionStrings:DefaultConnection=Server=sqldata;Initial Catalog=ApplicationDatabase;User Id=sa;Password=${DATABASE_PASSWORD};Connect Timeout=30;Encrypt=False;Trust Server Certificate=False;Application Intent=ReadWrite;Multi Subnet Failover=False
      - InitialSetup:AdminAccountEMail=${ADMIN_ACCOUNT_EMAIL}
      - InitialSetup:AdminAccountUsername=${ADMIN_ACCOUNT_USERNAME}
      - InitialSetup:AdminAccountPassword=${ADMIN_ACCOUNT_PASSWORD}
      - EmailService:Host=${EMAIL_HOST}
      - EmailService:Port=${EMAIL_PORT}
      - EmailService:EnableSSL=${EMAIL_USESSL}
      - EmailService:UserName=${EMAIL_USERNAME}
      - EmailService:Password=${EMAIL_PASSWORD}
  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - MSSQL_SA_PASSWORD=${DATABASE_PASSWORD}
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "5434:1433"
      