using ImbaBetWeb.Model;
using Microsoft.Data.SqlClient;
using System.Data;

namespace ImbaBetWeb.DataAccess
{
    public abstract class SqlStoreBase<T, U>()
        where T : IIdentifiable<U>
        where U : notnull
    {
        public abstract string TableName { get; }
        protected abstract string ConnectionString { get; }

        public abstract Dictionary<SqlColumnDefinition, object?> GetParameters(T source);
        public abstract Dictionary<SqlColumnDefinition, Action<T, dynamic?>> GetPropertyMap();


        public virtual Task<U> CreateAsync(T item)
        {
            return CreateAsync(item, false);
        }

        protected async Task<U> CreateAsync(T item, bool useGivenPrimary)
        {
            using var connection = new SqlConnection(ConnectionString);
            using var command = connection.CreateCommand();

            // Ignore the primary key column for inserts (assumed to be identity)
            var parameters = GetParameters(item).Where(x => x.Key.IsPrimaryKey == false || useGivenPrimary).ToDictionary();

            var columns = string.Join(",", parameters.Keys.Select(k => $"[{k.ColumnName}]"));
            var values = string.Join(",", parameters.Keys.Select(k => $"@{k.ColumnName}"));

            command.CommandText = $"INSERT INTO {TableName} ({columns}) VALUES ({values}); SELECT CONVERT(int,SCOPE_IDENTITY());";

            foreach (var param in parameters)
            {
                command.Parameters.Add($"@{param.Key.ColumnName}", param.Key.DbType, param.Key.Size).Value = param.Value ?? DBNull.Value;
            }

            await connection.OpenAsync();
            await command.PrepareAsync();
            var result = await command.ExecuteScalarAsync();
            await connection.CloseAsync();

            if (result == null)
                throw new InvalidOperationException("Error while creating new item. Could not get primary key.");

            // If we used the given primary key, return it; otherwise, return the one generated by the database.
            // potential bug: this assumes the primary key is of type int (see command text). If the primary key is not int, the cast will fail.
            return useGivenPrimary ? item.Id : (U)result;
        }

        public async Task UpdateAsync(T source)
        {
            using var connection = new SqlConnection(ConnectionString);
            using var command = connection.CreateCommand();

            var allParameters = GetParameters(source);
            var primary = allParameters.Single(kv => kv.Key.IsPrimaryKey);
            var nonPrimary = allParameters.Where(kv => kv.Key.IsPrimaryKey == false).ToDictionary();

            var setItems = string.Join(",", nonPrimary.Keys.Select(k => $"[{k.ColumnName}]=@{k.ColumnName}"));

            command.CommandText = $"UPDATE {TableName} " +
                $"SET {setItems} " +
                $"WHERE [{primary.Key.ColumnName}]=@{primary.Key.ColumnName}";

            foreach (var param in allParameters)
            {
                command.Parameters.Add($"@{param.Key.ColumnName}", param.Key.DbType, param.Key.Size).Value = param.Value ?? DBNull.Value;
            }

            await connection.OpenAsync();
            await command.PrepareAsync();
            await command.ExecuteNonQueryAsync();
            await connection.CloseAsync();
        }

        public async Task DeleteAsync(T source)
        {
            using var connection = new SqlConnection(ConnectionString);
            using var command = connection.CreateCommand();

            var primary = GetParameters(source).Single(kv => kv.Key.IsPrimaryKey);

            command.CommandText =
                $"DELETE FROM {TableName} " +
                $"WHERE [{primary.Key.ColumnName}]=@{primary.Key.ColumnName}";

            command.Parameters.Add($"@{primary.Key.ColumnName}", primary.Key.DbType, primary.Key.Size).Value = source.Id;

            await connection.OpenAsync();
            await command.PrepareAsync();
            await command.ExecuteNonQueryAsync();
            await connection.CloseAsync();
        }

        public async Task DeleteAllAsync()
        {
            using var connection = new SqlConnection(ConnectionString);
            using var command = connection.CreateCommand();

            command.CommandText = $"DELETE FROM {TableName}";

            await connection.OpenAsync();
            await command.ExecuteNonQueryAsync();
            await connection.CloseAsync();
        }

        public async Task<T> GetAsync(U id)
        {
            using var connection = new SqlConnection(ConnectionString);
            using var command = connection.CreateCommand();

            var columns = GetPropertyMap().Keys;
            var primary = columns.Single(kv => kv.IsPrimaryKey);

            command.CommandText = $"SELECT * FROM {TableName} WHERE [{primary.ColumnName}]=@{primary.ColumnName}";
            command.Parameters.Add($"@{primary.ColumnName}", primary.DbType, primary.Size).Value = id;

            await connection.OpenAsync();
            await command.PrepareAsync();
            var reader = await command.ExecuteReaderAsync();

            var ordinals = columns.ToDictionary(c => c, c => reader.GetOrdinal(c.ColumnName));

            await reader.ReadAsync();
            var item = ReadToItem(reader, ordinals);
            await connection.CloseAsync();

            return item;
        }

        public async Task<IEnumerable<T>> GetAllAsync()
        {
            using var connection = new SqlConnection(ConnectionString);
            using var command = connection.CreateCommand();

            var columns = GetPropertyMap().Keys;
            var primary = columns.Single(kv => kv.IsPrimaryKey);

            command.CommandText = $"SELECT * FROM {TableName}";

            await connection.OpenAsync();
            await command.PrepareAsync();
            var reader = await command.ExecuteReaderAsync();

            var ordinals = columns.ToDictionary(c => c, c => reader.GetOrdinal(c.ColumnName));

            var list = new List<T>();

            while (await reader.ReadAsync())
            {
                var item = ReadToItem(reader, ordinals);
                list.Add(item);
            }

            await connection.CloseAsync();
            return list;
        }

        public T ReadToItem(SqlDataReader reader, Dictionary<SqlColumnDefinition, int> ordinals)
        {
            var map = GetPropertyMap();
            T item = Activator.CreateInstance<T>();

            foreach (var ordinal in ordinals)
            {
                var column = ordinal.Key;
                var index = ordinal.Value;
                if (reader.IsDBNull(index))
                {
                    map[column](item, null);
                }
                else
                {
                    switch (column.DbType)
                    {
                        case SqlDbType.Int:
                            map[column](item, reader.GetInt32(index));
                            break;
                        case SqlDbType.NVarChar:
                            map[column](item, reader.GetString(index));
                            break;
                        case SqlDbType.Bit:
                            map[column](item, reader.GetBoolean(index));
                            break;
                        case SqlDbType.DateTime2:
                            map[column](item, reader.GetDateTime(index));
                            break;
                        default:
                            throw new InvalidOperationException($"Unsupported SqlDbType: {column.DbType}");
                    }
                }
            }

            return item;
        }

        public async Task EnsureInitializedAsync()
        {
            if (await TableExistsAsync())
                return;

            await CreateTableAsync();
        }

        protected async Task<bool> TableExistsAsync()
        {
            using var connection = new SqlConnection(ConnectionString);
            using var tableExistsCommand = connection.CreateCommand();
            tableExistsCommand.CommandText = $"SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = @{TableName}";
            tableExistsCommand.Parameters.Add($"@{TableName}", SqlDbType.NVarChar, 256).Value = TableName;

            await connection.OpenAsync();
            await tableExistsCommand.PrepareAsync();
            var result = await tableExistsCommand.ExecuteScalarAsync();
            await connection.CloseAsync();

            if (result == null)
                throw new InvalidOperationException("Error checking if table exists.");

            return (int)result > 0;
        }

        protected async Task CreateTableAsync()
        {
            using var connection = new SqlConnection(ConnectionString);

            using var createTableCommand = connection.CreateCommand();
            createTableCommand.CommandText = CreateTableCommandText();

            await connection.OpenAsync();
            await createTableCommand.PrepareAsync();
            await createTableCommand.ExecuteNonQueryAsync();
            await connection.CloseAsync();
        }

        private string CreateTableCommandText()
        {
            return
                $"CREATE TABLE {TableName} " +
                $"(" +
                    string.Join(", ", GetPropertyMap().Keys.Select(col =>
                    {
                        var identityPart = col.IsPrimaryKey && col.DbType == SqlDbType.Int ? "IDENTITY(1,1)" : "";
                        var primaryKeyPart = col.IsPrimaryKey ? "PRIMARY KEY" : "";
                        var sizePart = col.DbType == SqlDbType.NVarChar ? $"({col.Size})" : "";
                        var nullablePart = col.IsNullable ? "NULL" : "NOT NULL";
                        
                        return $"[{col.ColumnName}] {col.DbType}{sizePart} {nullablePart} {identityPart} {primaryKeyPart} ".Trim();
                    }))
                + " )";

        }
    }
}