name: Build and Publish image to Docker Hub - Experimental
on:
 [workflow_dispatch]

jobs:
 publish_images:
  runs-on: ubuntu-latest
  steps:
  - name: checkout
    uses: actions/checkout@v4
  - name: build image
    run: docker build -t 1337festor/imbabetweb:experimental -f ImbaBetWeb/Dockerfile .
  - name: push image to docker hub
    run: |
         docker login -u 1337festor -p ${{secrets.DOCKER_HUB_TOKEN}}
         docker push 1337festor/imbabetweb:experimental