name: Build project and run tests
on:
 push:
  branches:
   - master

jobs:
 build-test:
  name: Build and Test
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Setup dotnet
    uses: actions/setup-dotnet@v4
    with:
      dotnet-version: '8.0.x'

  - name: Install dependencies
    run: dotnet restore

  - name: Build
    run: dotnet build --no-restore

  - name: Test with the dotnet CLI
    run: dotnet test --no-build

  - name: Upload Allure Results
    uses: actions/upload-artifact@v4.0.0
    with:
      name: allure-results
      path: ./ImbaBetWeb.Test/bin/Debug/net8.0/allure-results
      if-no-files-found: error
      retention-days: 20

  - name: Clean up gh-pages branch (optional)
    continue-on-error: true  
    run: |
      git checkout -B gh-pages
      git rm -rf .
    

 report:
  name: Report Generation
  needs: build-test
  runs-on: ubuntu-latest
  steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: allure-results
        path: ./allure-results
  
    - name: Get Allure history (optional)
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
  
    - name: Generate report
      uses: simple-elf/allure-report-action@v1.12
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        gh_pages: allure-report
        allure_history: allure-history
        keep_reports: 20
  
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4.0.0
      with:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-report

    
