name: Build docker image and publish to Docker Hub
on:
 release:
  types: [published]

jobs:
 publish_images:
  name: Publish images
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v4
  - name: Build image
    run: docker build -t 1337festor/imbabetweb:latest -t 1337festor/imbabetweb:experimental -t 1337festor/imbabetweb:${{github.event.release.tag_name}} -f ImbaBetWeb/Dockerfile .
  - name: Push image to Docker Hub
    run: |
         docker login -u 1337festor -p ${{secrets.DOCKER_HUB_TOKEN}}
         docker push 1337festor/imbabetweb:${{github.event.release.tag_name}}
         docker push 1337festor/imbabetweb:latest
         docker push 1337festor/imbabetweb:experimental