name: Build docker image and publish to Docker Hub - Experimental
on:
 push:
  branches:
   - master

jobs:
 publish_images:
  name: Publish images
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v4
  - name: Build image
    run: docker build -t 1337festor/imbabetweb:experimental -f ImbaBetWeb/Dockerfile .
  - name: Push image to Docker Hub
    run: |
         docker login -u 1337festor -p ${{secrets.DOCKER_HUB_TOKEN}}
         docker push 1337festor/imbabetweb:experimental